sudo: false
language: ruby
cache:
  - apt
rvm:
  - 2.5.6

gemfile:
  - Gemfile-rails-4.2.x
  - Gemfile-rails-5.0.x
  - Gemfile-rails-5.1.x

before_install:
  - gem update --system
  - gem uninstall -v '>= 2' -i $(rvm gemdir)@global -ax bundler || true
  - gem install bundler -v '< 2'
  - bundle --version

notifications:
  email: false

script: "bundle exec rspec spec --color --profile"

env:
  global:
    - BUNDLER_VERSION=1.17.3
